### ISSUE TITLE
Asks for openssh-askpass when connecting to remove qemu kvm host OS X

### ISSUE THREAD

**Issue by valentin-nasta** [mbentley/docker-virt-manager#3]
Hi @mbentley I've tried this docker image but it's still asking for the openssh-askpass package.

![docker-virt-manager](https://cloud.githubusercontent.com/assets/2648486/21846770/ea0093f0-d7f8-11e6-9ad3-d958099b4215.png)

Details traceback:
```
Unable to connect to libvirt.

You need to install openssh-askpass or similar
to connect to this host.

Libvirt URI is: qemu+ssh://root@lxdomain/system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 904, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: Cannot recv data: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
Host key verification failed.: Connection reset by peer
```

**Comment by valentin-nasta** [comment]
For some reason should be `/usr/lib/ssh/ssh-askpass` and not `/usr/lib/ssh/gtk-ssh-askpass`.

**Comment by mbentley** [comment]
OK Ill have to take a look. I didn't get the chance to fully test it.

**Comment by mbentley** [comment]
I temporarily pushed a previous image I had when originally investigating this issue that you can use as a work around until I can find a fix: `mbentley/virt-manager:legacy`
