### ISSUE TITLE
Missing libGL

### ISSUE THREAD

**Issue by pgiblock** [mbentley/docker-virt-manager#6]
Currently failing as libGL is missing from the container:

```
$ docker run -e DISPLAY=10.0.0.64:0 -v ~/.ssh/id_rsa:/root/.ssh/id_rsa mbentley/virt-manager
Couldn't open libGL.so.1: Error loading shared library libGL.so.1: No such file or directory
```

I'd fix it, but I'm a noob.

**Comment by mbentley** [comment]
I'm guessing the Dockerfile needs the package `mesa-gl` added which provides `libGL.so.1`

**Comment by mbentley** [comment]
The new image should be building on Docker Hub now; let me know if that didn't fix it.

**Comment by pgiblock** [comment]
Works for me! Thanks. Now I realize ESXi support in virsh stinks. Time to look into migrating to KVM/QEMU.
